[versions]
# Plugins
androidGradlePlugin = "8.2.2"
kotlinPlugin = "1.9.22"
ksp = "1.9.22-1.0.17"
hilt = "2.48"
room = "2.6.1"

# Libraries
kotlinCompilerExtension = "1.5.8"
ktx = "1.12.0"
appcompat = "1.6.1"
activityCompose = "1.8.2"
navigationCompose = "2.7.5"
material = "1.10.0"
hiltNavigationCompose = "1.1.0"
lifecycle = "2.7.0"
kotlinxSerializationJson = "1.6.0"
retrofit = "2.9.0"
okhttp = "4.12.0"
loggingInterceptor = "4.12.0"
compose-bom = "2023.10.01"
firebase-bom = "32.7.0"
testJunit = "4.13.2"
androidxTestJunit = "1.1.5"
androidxTestEspresso = "3.5.1"
dataStore = "1.0.0"
coil-bom = "2.6.0"
coroutinesCore = "1.7.3"
material3 = "1.1.2"
paging = "3.2.1"
pagingCompose = "3.2.1"
googleServices = "4.4.0"
crashlytics = "2.9.9"
biometric = "1.1.0"
lottie = "6.1.0"
accompanist = "0.32.0"
workRuntimeKtx = "2.9.0"

[libraries]
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version = "1.0.1" }
androidx-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "ktx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
android-material = { module = "com.google.android.material:material", version.ref = "material" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version = "1.0.0" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "loggingInterceptor" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
material = { group = "androidx.compose.material", name = "material" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "dataStore" }
coil-bom = { group = "io.coil-kt", name = "coil-bom", version.ref = "coil-bom" }
coil = { group = "io.coil-kt", name = "coil-compose" }
test-junit = { group = "junit", name = "junit", version.ref = "testJunit" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestJunit" }
androidx-test-espresso = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxTestEspresso" }
androidx-biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
lottie = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }
google-accompanist = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
paging-runtime = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "pagingCompose" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "lifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
com-android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinPlugin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinPlugin" }
ksp-android = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics" }
room = { id = "androidx.room", version.ref = "room" }
